/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSearchPanel: typeof import('./../components/AdvancedSearchPanel.vue')['default']
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    AutoCopyControl: typeof import('./../components/AutoCopyControl.vue')['default']
    BetterGmailControl: typeof import('./../components/BetterGmailControl.vue')['default']
    Changelog: typeof import('./../components/Changelog.vue')['default']
    ContextMenu: typeof import('./../components/ContextMenu.vue')['default']
    DarkModeControl: typeof import('./../components/DarkModeControl.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    DragOpenControl: typeof import('./../components/DragOpenControl.vue')['default']
    FeedEradicatorControl: typeof import('./../components/FeedEradicatorControl.vue')['default']
    HideElementControl: typeof import('./../components/HideElementControl.vue')['default']
    InfiniteScrollControl: typeof import('./../components/InfiniteScrollControl.vue')['default']
    InstagramSavedLibrary: typeof import('./../components/InstagramSavedLibrary.vue')['default']
    Install: typeof import('./../components/install.vue')['default']
    InstantOCRControl: typeof import('./../components/InstantOCRControl.vue')['default']
    IPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IPhDotsThreeVertical: typeof import('~icons/ph/dots-three-vertical')['default']
    IPhGear: typeof import('~icons/ph/gear')['default']
    IPhGlobe: typeof import('~icons/ph/globe')['default']
    IPhListHeart: typeof import('~icons/ph/list-heart')['default']
    IPhMinus: typeof import('~icons/ph/minus')['default']
    IPhMoon: typeof import('~icons/ph/moon')['default']
    IPhPlus: typeof import('~icons/ph/plus')['default']
    IPhPresentationChart: typeof import('~icons/ph/presentation-chart')['default']
    IPhQuestion: typeof import('~icons/ph/question')['default']
    IPhRocketLaunch: typeof import('~icons/ph/rocket-launch')['default']
    IPhSun: typeof import('~icons/ph/sun')['default']
    LinksExplorerControl: typeof import('./../components/LinksExplorerControl.vue')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    LocaleSwitch: typeof import('./../components/LocaleSwitch.vue')['default']
    MinimalTwitterControl: typeof import('./../components/MinimalTwitterControl.vue')['default']
    QuickActionsControl: typeof import('./../components/QuickActionsControl.vue')['default']
    ReaderModeControl: typeof import('./../components/ReaderModeControl.vue')['default']
    ReloadAllTabsControl: typeof import('./../components/ReloadAllTabsControl.vue')['default']
    RichCopyControl: typeof import('./../components/RichCopyControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SearchJumperUI: typeof import('./../components/SearchJumperUI.vue')['default']
    SettingsDialog: typeof import('./../components/SettingsDialog.vue')['default']
    SocialAnalysisControl: typeof import('./../components/SocialAnalysisControl.vue')['default']
    SpeedBrowsingControl: typeof import('./../components/SpeedBrowsingControl.vue')['default']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwatch: typeof import('./../components/ThemeSwatch.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
    TimeSelector: typeof import('./../components/TimeSelector.vue')['default']
    ToolGlowsBar: typeof import('./../components/ToolGlowsBar.vue')['default']
    Update: typeof import('./../components/update.vue')['default']
    WordCounterPopup: typeof import('./../components/WordCounterPopup.vue')['default']
  }
}
